;; theme file, written [insert date here]
;; created by GimpMill -- DO NOT EDIT!

(require 'make-theme)

(let
	(
		(patterns-alist
		 '(
				("left-border" ;; 6 x 37
					(inactive "left-border-inactive.png")
					(focused "left-border.png")
					(highlighted "left-border-highlighted.png")
					(clicked "left-border-clicked.png")
				)
				("right-border" ;; 6 x 37
					(inactive "right-border-inactive.png")
					(focused "right-border.png")
					(highlighted "right-border-highlighted.png")
					(clicked "right-border-clicked.png")
				)
				("bottom-border" ;; 190 x 6
					(inactive "bottom-border-inactive.png")
					(focused "bottom-border.png")
					(highlighted "bottom-border-highlighted.png")
					(clicked "bottom-border-clicked.png")
				)
				("top-left" ;; 8 x 20
					(inactive "top-left-inactive.png")
					(focused "top-left.png")
					(highlighted "top-left-highlighted.png")
					(clicked "top-left-clicked.png")
				)
				("top-right" ;; 8 x 20
					(inactive "top-right-inactive.png")
					(focused "top-right.png")
					(highlighted "top-right-highlighted.png")
					(clicked "top-right-clicked.png")
				)
				("bottom-left" ;; 12 x 12
					(inactive "bottom-left-inactive.png")
					(focused "bottom-left.png")
					(highlighted "bottom-left-highlighted.png")
					(clicked "bottom-left-clicked.png")
				)
				("bottom-right" ;; 12 x 12
					(inactive "bottom-right-inactive.png")
					(focused "bottom-right.png")
					(highlighted "bottom-right-highlighted.png")
					(clicked "bottom-right-clicked.png")
				)
				("title-left" ;; 7 x 25
					(inactive "title-left-inactive.png")
					(focused "title-left.png")
					(highlighted "title-left-highlighted.png")
					(clicked "title-left-clicked.png")
				)
				("title-right" ;; 7 x 25
					(inactive "title-right-inactive.png")
					(focused "title-right.png")
					(highlighted "title-right-highlighted.png")
					(clicked "title-right-clicked.png")
				)
				("title" ;; 96 x 27
					(inactive "title-inactive.png")
					(focused "title.png")
					(highlighted "title-highlighted.png")
					(clicked "title-clicked.png")
				)
				("min-button" ;; 22 x 20
					(inactive "min-button-inactive.png")
					(focused "min-button.png")
					(highlighted "min-button-highlighted.png")
					(clicked "min-button-clicked.png")
				)
				("max-button" ;; 22 x 20
					(inactive "max-button-inactive.png")
					(focused "max-button.png")
					(highlighted "max-button-highlighted.png")
					(clicked "max-button-clicked.png")
				)
				("close-button" ;; 22 x 20
					(inactive "close-button-inactive.png")
					(focused "close-button.png")
					(highlighted "close-button-highlighted.png")
					(clicked "close-button-clicked.png")
				)
				("menu-button" ;; 22 x 20
					(inactive "menu-button-inactive.png")
					(focused "menu-button.png")
					(highlighted "menu-button-highlighted.png")
					(clicked "menu-button-clicked.png")
				)

			)
		)
		(frames-alist
		 '(
				("normal"
					(
						(background . "left-border")
						(left-edge . -6)
						(top-edge . 0)
						(bottom-edge . 6)
						(class . left-border)
					)
					(
						(background . "right-border")
						(right-edge . -6)
						(top-edge . 0)
						(bottom-edge . 6)
						(class . right-border)
					)
					(
						(background . "bottom-border")
						(left-edge . 6)
						(right-edge . 6)
						(bottom-edge . -6)
						(class . bottom-border)
					)
					(
						(background . "top-left")
						(left-edge . -6)
						(top-edge . -20)
						(class . top-left-corner)
					)
					(
						(background . "top-right")
						(right-edge . -6)
						(top-edge . -20)
						(class . top-right-corner)
					)
					(
						(background . "bottom-left")
						(left-edge . -6)
						(bottom-edge . -6)
						(class . bottom-left-corner)
					)
					(
						(background . "bottom-right")
						(right-edge . -6)
						(bottom-edge . -6)
						(class . bottom-right-corner)
					)
					(
						(background . "title-left")
						(left-edge . 24)
						(top-edge . -25)
						(class . title)
					)
					(
						(background . "title-right")
						(right-edge . 68)
						(top-edge . -25)
						(class . title)
					)
					(
						(background . "title")
						(left-edge . 31)
						(right-edge . 75)
						(top-edge . -27)
						(class . title)
						(text . window-name)
						(x-justify . center)
						(y-justify . center)
						(foreground . ("blue" "white"))
					)
					(
						(background . "min-button")
						(right-edge . 46)
						(top-edge . -20)
						(class . iconify-button)
					)
					(
						(background . "max-button")
						(right-edge . 24)
						(top-edge . -20)
						(class . maximize-button)
					)
					(
						(background . "close-button")
						(right-edge . 2)
						(top-edge . -20)
						(class . close-button)
					)
					(
						(background . "menu-button")
						(left-edge . 2)
						(top-edge . -20)
						(class . menu-button)
					)
				)				("shaped"
					(
						(background . "top-left")
						(left-edge . -6)
						(top-edge . -20)
						(class . top-left-corner)
					)
					(
						(background . "top-right")
						(right-edge . -6)
						(top-edge . -20)
						(class . top-right-corner)
					)
					(
						(background . "title-left")
						(left-edge . 24)
						(top-edge . -25)
						(class . title)
					)
					(
						(background . "title-right")
						(right-edge . 68)
						(top-edge . -25)
						(class . title)
					)
					(
						(background . "title")
						(left-edge . 31)
						(right-edge . 75)
						(top-edge . -27)
						(class . title)
						(text . window-name)
						(x-justify . center)
						(y-justify . center)
						(foreground . ("blue" "white"))
					)
					(
						(background . "min-button")
						(right-edge . 46)
						(top-edge . -20)
						(class . iconify-button)
					)
					(
						(background . "max-button")
						(right-edge . 24)
						(top-edge . -20)
						(class . maximize-button)
					)
					(
						(background . "close-button")
						(right-edge . 2)
						(top-edge . -20)
						(class . close-button)
					)
					(
						(background . "menu-button")
						(left-edge . 2)
						(top-edge . -20)
						(class . menu-button)
					)
				)				("transient"
					(
						(background . "left-border")
						(left-edge . -6)
						(top-edge . 0)
						(bottom-edge . 6)
						(class . left-border)
					)
					(
						(background . "right-border")
						(right-edge . -6)
						(top-edge . 0)
						(bottom-edge . 6)
						(class . right-border)
					)
					(
						(background . "bottom-border")
						(left-edge . 6)
						(right-edge . 6)
						(bottom-edge . -6)
						(class . bottom-border)
					)
					(
						(background . "top-left")
						(left-edge . -6)
						(top-edge . -20)
						(class . top-left-corner)
					)
					(
						(background . "top-right")
						(right-edge . -6)
						(top-edge . -20)
						(class . top-right-corner)
					)
					(
						(background . "bottom-left")
						(left-edge . -6)
						(bottom-edge . -6)
						(class . bottom-left-corner)
					)
					(
						(background . "bottom-right")
						(right-edge . -6)
						(bottom-edge . -6)
						(class . bottom-right-corner)
					)
					(
						(background . "title-left")
						(left-edge . 24)
						(top-edge . -25)
						(class . title)
					)
					(
						(background . "title-right")
						(right-edge . 68)
						(top-edge . -25)
						(class . title)
					)
					(
						(background . "title")
						(left-edge . 31)
						(right-edge . 75)
						(top-edge . -27)
						(class . title)
						(text . window-name)
						(x-justify . center)
						(y-justify . center)
						(foreground . ("blue" "white"))
					)
					(
						(background . "min-button")
						(right-edge . 46)
						(top-edge . -20)
						(class . iconify-button)
					)
					(
						(background . "max-button")
						(right-edge . 24)
						(top-edge . -20)
						(class . maximize-button)
					)
					(
						(background . "close-button")
						(right-edge . 2)
						(top-edge . -20)
						(class . close-button)
					)
					(
						(background . "menu-button")
						(left-edge . 2)
						(top-edge . -20)
						(class . menu-button)
					)
				)				("shaped-transient"
					(
						(background . "top-left")
						(left-edge . -6)
						(top-edge . -20)
						(class . top-left-corner)
					)
					(
						(background . "top-right")
						(right-edge . -6)
						(top-edge . -20)
						(class . top-right-corner)
					)
					(
						(background . "title-left")
						(left-edge . 24)
						(top-edge . -25)
						(class . title)
					)
					(
						(background . "title-right")
						(right-edge . 68)
						(top-edge . -25)
						(class . title)
					)
					(
						(background . "title")
						(left-edge . 31)
						(right-edge . 75)
						(top-edge . -27)
						(class . title)
						(text . window-name)
						(x-justify . center)
						(y-justify . center)
						(foreground . ("blue" "white"))
					)
					(
						(background . "min-button")
						(right-edge . 46)
						(top-edge . -20)
						(class . iconify-button)
					)
					(
						(background . "max-button")
						(right-edge . 24)
						(top-edge . -20)
						(class . maximize-button)
					)
					(
						(background . "close-button")
						(right-edge . 2)
						(top-edge . -20)
						(class . close-button)
					)
					(
						(background . "menu-button")
						(left-edge . 2)
						(top-edge . -20)
						(class . menu-button)
					)
				)				("unframed"
				)
			)
		)
		(mapping-alist
		 '(
				(default . "normal")
				(transient . "transient")
				(shaped . "shaped")
				(shaped-transient . "shaped-transient")
				(unframed . "nil")
			)
		)

		(theme-name 'aq3)
	)

	(add-frame-style theme-name 
		(make-theme patterns-alist frames-alist mapping-alist)
	)
	(when 
		(boundp 'mark-frame-style-editable)
		(mark-frame-style-editable theme-name)
	)
)
